[build]
base = "/"
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/api/*"
to = "http://funllm.sit.sf-express.com/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
